version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/outputs:/app/outputs
    environment:
      - MURF_API_KEY=${MURF_API_KEY}
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:5173
      - MAX_UPLOAD_SIZE=10485760
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm run dev -- --host 